name: econa_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.80+85

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.8
  hooks_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  flutter_hooks: 0.21.3+1
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  go_router: 16.3.0
  flutter_svg: 2.2.3
  flutter_inset_shadow: 2.0.3
  fl_chart: 0.71.0
  firebase_core: 3.15.2
  firebase_auth: 5.7.0
  cloud_firestore: 5.6.12
  firebase_messaging: 15.2.10
  google_sign_in: 7.2.0
  sign_in_with_apple: 6.1.4
  logger: 2.6.2
  flutter_riverpod: 2.6.1
  shared_preferences: 2.5.3
  flutter_line_sdk: 2.6.2
  nonce: 1.2.0
  crypto: 3.0.7
  protobuf: 4.2.0
  grpc: 4.1.0
  connectrpc: 0.4.1
  flutter_card_swiper: 7.2.0
  collection: ^1.19.0
  slang: 4.11.0
  slang_flutter: 4.11.0
  build_runner: 2.4.15
  image_picker: 1.2.1
  uuid: 4.5.2
  file_picker: 10.3.7
  intl: 0.20.2
  connectivity_plus: 6.1.5
  url_launcher: 6.3.2
  flutter_reorderable_grid_view: 5.5.2
  camera: 0.11.2+1
  permission_handler: 12.0.1
  animated_text_kit: 4.3.0
  purchases_flutter: 9.9.9
  envied: 1.3.1
  recaptcha_enterprise_flutter: 18.8.2
  flutter_secure_storage: 9.2.4
  sentry_flutter: 9.8.0
  webview_flutter: 4.13.0
  flutter_inappwebview: 6.1.5
  adjust_sdk: 5.4.5
  app_tracking_transparency: 2.0.6+1
  flutter_launcher_icons: 0.14.4
  firebase_remote_config: 5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 7.0.0
  custom_lint: 0.7.6
  riverpod_lint: 2.6.5
  riverpod_generator: 2.6.5
  freezed: 3.0.6
  json_serializable: 6.9.5
  go_router_builder: 3.0.1
  flutter_gen_runner: 5.12.0
  mocktail: 1.0.4
  envied_generator: 1.1.1

flutter_gen:
  output: lib/presentations/gen/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.png
  min_sdk_android: 31
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/illusts/
    - assets/images/photos/
    - assets/icon/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Medium.ttf
          weight: 600
